DROP TABLE COCHE_USADO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE  CASCADE CONSTRAINTS;
DROP TABLE COMPRA  CASCADE CONSTRAINTS;
DROP TABLE INCLUYE CASCADE CONSTRAINTS;
DROP TABLE COCHE_NUEVO  CASCADE CONSTRAINTS;
DROP TABLE DISPONIBLE  CASCADE CONSTRAINTS;
DROP TABLE OPCION  CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO  CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR  CASCADE CONSTRAINTS;
DROP TABLE MECANICO CASCADE CONSTRAINTS;
DROP TABLE ENTREGA  CASCADE CONSTRAINTS;

CREATE TABLE EMPLEADO(
	DNIE CHAR(9) CHECK (REGEXP_LIKE(DNIE,'^[0-9]{8}[A-Z]$')),
	Nombre VARCHAR2(30),
	Direccion VARCHAR2(50),
	Tlf NUMBER(9),
	Tipo CHAR(1) CHECK (Tipo IN ('M','V')),
	PRIMARY KEY (DNIE)
);

CREATE TABLE VENDEDOR (
	DNIE CHAR(9),
	PRIMARY KEY(DNIE),
	FOREIGN KEY (DNIE) REFERENCES EMPLEADO(DNIE)
);

CREATE TABLE MECANICO (
	DNIE CHAR(9),
	PRIMARY KEY(DNIE),
	FOREIGN KEY (DNIE) REFERENCES EMPLEADO(DNIE)
);

CREATE TABLE COCHE_USADO(
	Matricula_Usado CHAR(7),
	Marca VARCHAR2(20),
	Modelo VARCHAR2(20),
	Precio_Trasaccion NUMBER(8,2),
	DNIE CHAR(9),
	PRIMARY KEY (Matricula_Usado),
	FOREIGN KEY (DNIE) REFERENCES MECANICO(DNIE)ON DELETE CASCADE
);

CREATE TABLE CLIENTE(
	DNIC CHAR(9) CHECK (REGEXP_LIKE(DNIC,'^[0-9]{8}[A-Z]$')),
	Nombre VARCHAR2(30),
	Direccion VARCHAR2(50),
	Tlf NUMBER(9),
	PRIMARY KEY (DNIC)
);

CREATE TABLE OPCION(
	IDO INTEGER,
	Nombre VARCHAR2(30),
	Descripcion VARCHAR2(50),
	PRIMARY KEY (IDO)
);

CREATE TABLE COCHE_NUEVO (
	IDV INTEGER,
	Marca VARCHAR2(20),
	Modelo VARCHAR2(20),
	Motor CHAR(1) CHECK (Motor IN('G','D','E','H')),
	Cilindrada NUMBER(4),
	Precio_Base NUMBER(8,2),
	PRIMARY KEY (IDV)
);

CREATE TABLE DISPONIBLE(
	IDV INTEGER,
	IDO INTEGER,
	Precio_Opcion NUMBER(7,2),
	PRIMARY KEY (IDV,IDO),
	FOREIGN KEY (IDV) REFERENCES COCHE_NUEVO(IDV) ON DELETE CASCADE,
	FOREIGN KEY (IDO) REFERENCES OPCION(IDO) ON DELETE CASCADE
);

CREATE TABLE COMPRA (
	IDC INTEGER,
	DNIC CHAR(9),
	IDV INTEGER,
	DNIE CHAR(9),
	PRIMARY KEY(IDC),
	FOREIGN KEY(DNIC) REFERENCES CLIENTE(DNIC) ON DELETE CASCADE,
	FOREIGN KEY(IDV) REFERENCES COCHE_NUEVO(IDV) ON DELETE CASCADE,
	FOREIGN KEY(DNIE) REFERENCES VENDEDOR(DNIE) ON DELETE CASCADE
);

CREATE TABLE ENTREGA(
	IDC INTEGER,
	Matricula_Usado CHAR(7) CHECK (REGEXP_LIKE(Matricula_Usado,'^[0-9]{4}[A-Z]{3}$')),
	PRIMARY KEY (IDC),
	FOREIGN KEY (IDC) REFERENCES COMPRA (IDC) ON DELETE CASCADE,
	FOREIGN KEY (Matricula_Usado) REFERENCES COCHE_USADO (Matricula_Usado) ON DELETE CASCADE
);

CREATE TABLE INCLUYE(
	IDC INTEGER,
	IDO INTEGER,
	Precio NUMBER(7,2),
	PRIMARY KEY(IDC,IDO),
	FOREIGN KEY(IDC) REFERENCES COMPRA(IDC) ON DELETE CASCADE,
	FOREIGN KEY(IDO) REFERENCES OPCION(IDO) ON DELETE CASCADE
);

-- INSERT CLIENTE
-- INSERT COCHE_USADO
